import { defineConfig } from 'vite';
import { resolve } from 'node:path';
import { htmlInclude } from './vite-plugins/html-include';

export default defineConfig({
  root: '.',
  publicDir: 'public',
  plugins: [htmlInclude(resolve(__dirname, 'partials'))],
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        konfigurator: resolve(__dirname, 'konfigurator.html'),
        polityka: resolve(__dirname, 'polityka.html'),
        kontakt: resolve(__dirname, 'kontakt.html'),
        dziekujemy: resolve(__dirname, 'dziekujemy.html'),
        notFound: resolve(__dirname, '404.html'),
        faq: resolve(__dirname, 'faq.html'),
        rozwiazaniaPieczywo: resolve(__dirname, 'rozwiazania/pieczywo.html'),
        rozwiazaniaJajka: resolve(__dirname, 'rozwiazania/jajka.html'),
        rozwiazaniaSery: resolve(__dirname, 'rozwiazania/sery.html'),
        rozwiazaniaZiemniakiWarzywa: resolve(__dirname, 'rozwiazania/ziemniaki-warzywa.html'),
        rozwiazaniaBioLokalne: resolve(__dirname, 'rozwiazania/bio-lokalne.html'),
        rozwiazaniaMiesoDania: resolve(__dirname, 'rozwiazania/mieso-dania.html'),
        rozwiazaniaNapoje: resolve(__dirname, 'rozwiazania/napoje.html'),
        jakDzialamy: resolve(__dirname, 'jak-dzialamy.html'),
        oferta: resolve(__dirname, 'oferta.html'),
        automatySmart: resolve(__dirname, 'automaty-smart.html'),
        rozwiazaniaKwiaty: resolve(__dirname, 'rozwiazania/kwiaty.html'),
        rozwiazaniaCiastka: resolve(__dirname, 'rozwiazania/ciastka.html'),
        rozwiazaniaWszystko: resolve(__dirname, 'rozwiazania/automat-na-wszystko.html'),
        automatDlaFirmy: resolve(__dirname, 'automat-dla-firmy.html'),
        finansowanie: resolve(__dirname, 'finansowanie.html'),
        automatySielaff: resolve(__dirname, 'automaty-sielaff.html'),
        poradnik: resolve(__dirname, 'poradnik.html'),
        poradnikJajka: resolve(__dirname, 'poradnik/ile-kosztuje-automat-na-jajka.html'),
        poradnikChleb: resolve(__dirname, 'poradnik/automat-na-chleb-jak-dziala.html'),
        poradnikWynajem: resolve(__dirname, 'poradnik/wynajem-czy-zakup-automatu-vendingowego.html'),
        poradnikFirmy: resolve(__dirname, 'poradnik/automat-vendingowy-do-biura-szkoly-zakladu.html'),
        poradnikKwiatomat: resolve(__dirname, 'poradnik/kwiatomat-sprzedaz-kwiatow-z-automatu.html'),
        poradnikPrzepisy: resolve(__dirname, 'poradnik/sprzedaz-zywnosci-z-automatu-przepisy.html'),
        i18n_en_index: resolve(__dirname, 'en/index.html'),
        i18n_en_offer: resolve(__dirname, 'en/offer.html'),
        i18n_en_inquiry: resolve(__dirname, 'en/inquiry.html'),
        i18n_en_sielaff_machines: resolve(__dirname, 'en/sielaff-machines.html'),
        i18n_en_thank_you: resolve(__dirname, 'en/thank-you.html'),
        i18n_en_solutions_bread: resolve(__dirname, 'en/solutions/bread.html'),
        i18n_en_solutions_eggs: resolve(__dirname, 'en/solutions/eggs.html'),
        i18n_en_solutions_cheese_dairy: resolve(__dirname, 'en/solutions/cheese-dairy.html'),
        i18n_en_solutions_potatoes_vegetables: resolve(__dirname, 'en/solutions/potatoes-vegetables.html'),
        i18n_en_solutions_organic_local: resolve(__dirname, 'en/solutions/organic-local.html'),
        i18n_en_solutions_meat_ready_meals: resolve(__dirname, 'en/solutions/meat-ready-meals.html'),
        i18n_en_solutions_drinks: resolve(__dirname, 'en/solutions/drinks.html'),
        i18n_en_solutions_flowers: resolve(__dirname, 'en/solutions/flowers.html'),
        i18n_en_solutions_cakes: resolve(__dirname, 'en/solutions/cakes.html'),
        i18n_en_solutions_anything: resolve(__dirname, 'en/solutions/anything.html'),
        i18n_cs_index: resolve(__dirname, 'cs/index.html'),
        i18n_cs_nabidka: resolve(__dirname, 'cs/nabidka.html'),
        i18n_cs_poptavka: resolve(__dirname, 'cs/poptavka.html'),
        i18n_cs_automaty_sielaff: resolve(__dirname, 'cs/automaty-sielaff.html'),
        i18n_cs_dekujeme: resolve(__dirname, 'cs/dekujeme.html'),
        i18n_cs_reseni_pecivo: resolve(__dirname, 'cs/reseni/pecivo.html'),
        i18n_cs_reseni_vejce: resolve(__dirname, 'cs/reseni/vejce.html'),
        i18n_cs_reseni_syry_mlecne_vyrobky: resolve(__dirname, 'cs/reseni/syry-mlecne-vyrobky.html'),
        i18n_cs_reseni_brambory_zelenina: resolve(__dirname, 'cs/reseni/brambory-zelenina.html'),
        i18n_cs_reseni_bio_lokalni: resolve(__dirname, 'cs/reseni/bio-lokalni.html'),
        i18n_cs_reseni_maso_hotova_jidla: resolve(__dirname, 'cs/reseni/maso-hotova-jidla.html'),
        i18n_cs_reseni_napoje: resolve(__dirname, 'cs/reseni/napoje.html'),
        i18n_cs_reseni_kvetiny: resolve(__dirname, 'cs/reseni/kvetiny.html'),
        i18n_cs_reseni_zakusky: resolve(__dirname, 'cs/reseni/zakusky.html'),
        i18n_cs_reseni_cokoliv: resolve(__dirname, 'cs/reseni/cokoliv.html'),
        i18n_sk_index: resolve(__dirname, 'sk/index.html'),
        i18n_sk_ponuka: resolve(__dirname, 'sk/ponuka.html'),
        i18n_sk_dopyt: resolve(__dirname, 'sk/dopyt.html'),
        i18n_sk_automaty_sielaff: resolve(__dirname, 'sk/automaty-sielaff.html'),
        i18n_sk_dakujeme: resolve(__dirname, 'sk/dakujeme.html'),
        i18n_sk_riesenia_pecivo: resolve(__dirname, 'sk/riesenia/pecivo.html'),
        i18n_sk_riesenia_vajcia: resolve(__dirname, 'sk/riesenia/vajcia.html'),
        i18n_sk_riesenia_syry_mliecne_vyrobky: resolve(__dirname, 'sk/riesenia/syry-mliecne-vyrobky.html'),
        i18n_sk_riesenia_zemiaky_zelenina: resolve(__dirname, 'sk/riesenia/zemiaky-zelenina.html'),
        i18n_sk_riesenia_bio_lokalne: resolve(__dirname, 'sk/riesenia/bio-lokalne.html'),
        i18n_sk_riesenia_maso_hotove_jedla: resolve(__dirname, 'sk/riesenia/maso-hotove-jedla.html'),
        i18n_sk_riesenia_napoje: resolve(__dirname, 'sk/riesenia/napoje.html'),
        i18n_sk_riesenia_kvety: resolve(__dirname, 'sk/riesenia/kvety.html'),
        i18n_sk_riesenia_zakusky: resolve(__dirname, 'sk/riesenia/zakusky.html'),
        i18n_sk_riesenia_cokolvek: resolve(__dirname, 'sk/riesenia/cokolvek.html'),
      },
    },
  },
});
